FROM rust:1.86 AS orion-builder

#RUN rustup component add rustfmt

WORKDIR /tmp/orion

RUN <<EOF
apt update
apt install -y protobuf-compiler
EOF

COPY ./orion-configuration ./orion-configuration
COPY ./orion-data-plane-api ./orion-data-plane-api
COPY ./orion-error ./orion-error
COPY ./orion-lib ./orion-lib
COPY ./orion-proxy ./orion-proxy
COPY ./orion-xds ./orion-xds
COPY ./envoy-data-plane-api ./envoy-data-plane-api
COPY Cargo.toml ./
COPY Cargo.lock ./


RUN cargo build --release

### Split into two files; one to build and one to actually run it
###https://docs.docker.com/develop/develop-images/multistage-build/

FROM debian:bookworm-slim
RUN <<EOF
apt update
apt upgrade -y
EOF

COPY --from=orion-builder /tmp/orion/target/release/orion /orion
ENTRYPOINT ["/orion"]
